import { MailToLink, WebSiteLink } from '@components/shared/links';
import { Box, Link, Typography } from '@mui/material';
import Stack from '@mui/material/Stack';
import { useGetResponsiveFontVariants } from 'utils/hooks/responsiveFontVariant.util';

export default function MainContentEn(): JSX.Element {
  const getFontVariants = useGetResponsiveFontVariants();
  const titleVariant = getFontVariants({ medium: 'h5', large: 'h4' });
  const subtitleVariant = getFontVariants({ medium: 'h6', large: 'h5' });

  return (
    <Stack gap={{ xs: 2, md: 3, lg: 6 }} color="grey.800">
      <Stack gap={{ xs: 0.5, md: 1 }}>
        <Typography variant="body2">
          Wesner Software (“us”, “we”, or “our”) operates the <WebSiteLink />{' '}
          website (here and after referred to as the “Service”).
        </Typography>
        <Typography variant="body2">
          This page informs you of our policies regarding the collection, use
          and disclosure of personal data when you use our Service and the
          choices you have associated with that data.
        </Typography>
        <Typography variant="body2">
          We use your data to provide and improve the Service. By using the
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this Privacy
          Policy, the terms used in this Privacy Policy have the same meanings
          as in our Terms and Conditions, accessible from <WebSiteLink />
        </Typography>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Definitions
        </Typography>
        <Stack component="ul" gap={1}>
          <Typography variant="body2" component="li">
            <dfn>Service</dfn> is the <WebSiteLink /> website operated by Wesner
            Software.
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>Personal Data </dfn> means data about a living individual who
            can be identified from those data (or from those and other
            information either in our possession or likely to come into our
            possession).
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>Usage Data </dfn> is data collected automatically either
            generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>Cookies</dfn> are small files stored on your device (computer
            or mobile device).
          </Typography>
          <Typography variant="body2" component="li">
            <dfn> Data Controller</dfn> means the natural or legal person who
            (either alone or jointly or in common with other persons) determines
            the purposes for which and the manner in which any personal
            information are, or are to be, processed. For the purpose of this
            Privacy Policy, we are a Data Controller of your Personal Data.
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>Data Processors (or Service Providers)</dfn> means any natural
            or legal person who processes the data on behalf of the Data
            Controller.We may use the services of various Service Providers in
            order to process your data more effectively.
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>Data Subject (or User)</dfn> is any living individual who is
            using our Service and is the subject of Personal Data.
          </Typography>
        </Stack>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Information Collection and Use
        </Typography>
        <Typography variant="body2">
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </Typography>
      </Stack>

      <Stack gap={{ xs: 1, lg: 2 }}>
        <Typography variant={titleVariant} color="grey.900">
          Types of Data Collected
        </Typography>
        <Stack gap={1}>
          <Typography variant={subtitleVariant} color="grey.900">
            Personal Data
          </Typography>
          <Typography variant="body2">
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally identifiable information
            may include, but is not limited to:
          </Typography>
          <Stack component="ul" gap={{ xs: 0.5, md: 1 }}>
            <Typography component="li" variant="body2">
              Name
            </Typography>
            <Typography component="li" variant="body2">
              Email address
            </Typography>
          </Stack>
        </Stack>
        <Stack gap={1}>
          <Typography variant={subtitleVariant} color="grey.900">
            Usage Information
          </Typography>
          <Typography variant="body2">
            We may also collect information on how the Service is accessed and
            used (“Usage Data”). This Usage Data may include information such as
            your computer’s Internet Protocol address (e.g. IP address), browser
            type, browser version, the pages of our Service that you visit, the
            time and date of your visit, the time spent on those pages, unique
            device identifiers and other diagnostic data.
          </Typography>
        </Stack>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Tracking & Cookies Data
        </Typography>
        <Typography variant="body2">
          We use cookies and similar tracking technologies to track the activity
          on our Service and we hold certain information.
        </Typography>
        <Typography variant="body2">
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Other tracking technologies are
          also used such as beacons, tags and scripts to collect and track
          information and to improve and analyse our Service.
        </Typography>
        <Typography variant="body2">
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </Typography>
        <Typography variant="body2">Examples of Cookies we use:</Typography>
        <Stack component="ul" gap={1}>
          <Typography variant="body2" component="li">
            <dfn>Session Cookies.</dfn> We use Session Cookies to operate our
            Service.
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>Preference Cookies.</dfn> We use Preference Cookies to remember
            your preferences and various settings.
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>Security Cookies.</dfn> We use Security Cookies for security
            purposes.
          </Typography>
        </Stack>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Use of Data
        </Typography>
        <Typography variant="body2">
          Wesner Software uses the collected information for various purposes:
        </Typography>
        <Stack component="ul" gap={1}>
          <Typography variant="body2" component="li">
            To provide and maintain our Service.
          </Typography>
          <Typography variant="body2" component="li">
            To notify you about changes to our Service.
          </Typography>
          <Typography variant="body2" component="li">
            To allow you to participate in interactive features of our Service
            when you choose to do so.
          </Typography>
          <Typography variant="body2" component="li">
            To provide customer support.
          </Typography>
          <Typography variant="body2" component="li">
            To gather analysis or valuable information so that we can improve
            our Service.
          </Typography>
          <Typography variant="body2" component="li">
            To monitor the usage of our Service.
          </Typography>
          <Typography variant="body2" component="li">
            To detect, prevent and address technical issues.
          </Typography>
        </Stack>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Legal Basis for Processing Personal Data under the General Data
          Protection Regulation (GDPR)
        </Typography>
        <Typography variant="body2">
          If you are from the European Economic Area (EEA), Wesner Software
          legal basis for collecting and using the personal information
          described in this Privacy Policy depends on the Personal Data we
          collect and the specific context in which we collect it.
        </Typography>
        <Typography variant="body2">
          Wesner Software may process your Personal Data because:
        </Typography>
        <Stack component="ul" gap={1}>
          <Typography variant="body2" component="li">
            We need to perform a contract with you.
          </Typography>
          <Typography variant="body2" component="li">
            You have given us permission to do so.
          </Typography>
          <Typography variant="body2" component="li">
            The processing is in our legitimate interests and it is not
            overridden by your rights.
          </Typography>
          <Typography variant="body2" component="li">
            To comply with the law.
          </Typography>
        </Stack>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Retention of Data
        </Typography>
        <Typography variant="body2">
          Wesner Software will retain your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes and
          enforce our legal agreements and policies.
        </Typography>
        <Typography variant="body2">
          Wesner Software will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of our Service, or we are legally obligated
          to retain this data for longer periods.
        </Typography>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Transfer of Data
        </Typography>
        <Typography variant="body2">
          Your information, including Personal Data, may be transferred to — and
          maintained on — computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction.
        </Typography>
        <Typography variant="body2">
          If you are located outside Germany and choose to provide information
          to us, please note that we transfer the data, including Personal Data,
          to Germany and process it there.
        </Typography>
        <Typography variant="body2">
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </Typography>
        <Typography variant="body2">
          Wesner Software will take all the steps reasonably necessary to ensure
          that your data is treated securely and in accordance with this Privacy
          Policy and no transfer of your Personal Data will take place to an
          organisation or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </Typography>
      </Stack>

      <Stack gap={{ xs: 1, lg: 2 }}>
        <Typography variant={titleVariant} color="grey.900">
          Disclosure of Data
        </Typography>
        <Stack gap={1}>
          <Typography variant={subtitleVariant} color="grey.900">
            Business Transaction
          </Typography>
          <Typography variant="body2">
            If Wesner Software is involved in a merger, acquisition or asset
            sale, your Personal Data may be transferred. We will provide notice
            before your Personal Data is transferred and becomes subject to a
            different Privacy Policy.
          </Typography>
        </Stack>
        <Stack gap={1}>
          <Typography variant={subtitleVariant} color="grey.900">
            Disclosure for Law Enforcement
          </Typography>
          <Typography variant="body2">
            Under certain circumstances, Wesner Software may be required to
            disclose your Personal Data if required to do so by law or in
            response to valid requests by public authorities (e.g. a court or a
            government agency).
          </Typography>
        </Stack>
        <Stack gap={1}>
          <Typography variant={subtitleVariant} color="grey.900">
            Legal Requirements
          </Typography>
          <Typography variant="body2">
            Wesner Software may disclose your Personal Data in the good faith
            belief that such action is necessary:
          </Typography>
          <Stack component="ul" gap={{ xs: 0.5, md: 1 }}>
            <Typography component="li" variant="body2">
              To comply with a legal obligation.
            </Typography>
            <Typography component="li" variant="body2">
              To protect and defend the rights or property of Wesner Software.
            </Typography>
            <Typography component="li" variant="body2">
              To prevent or investigate possible wrongdoing in connection with
              the Service.
            </Typography>
            <Typography component="li" variant="body2">
              To protect the personal safety of users of the Service or the
              public.
            </Typography>
            <Typography component="li" variant="body2">
              To protect against legal liability.
            </Typography>
          </Stack>
        </Stack>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Security of Data
        </Typography>
        <Typography variant="body2">
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </Typography>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Our Policy on “Do Not Track” Signals under the California Online
          Protection Act (CalOPPA)
        </Typography>
        <Typography variant="body2">
          We do not support Do Not Track (“DNT”). Do Not Track is a preference
          you can set in your web browser to inform websites that you do not
          want to be tracked.
        </Typography>
        <Typography variant="body2">
          You can enable or disable Do Not Track by visiting the Preferences or
          Settings page of your web browser.
        </Typography>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Your Data Protection Rights under the General Data Protection
          Regulation (GDPR)
        </Typography>
        <Typography variant="body2">
          If you are a resident of the European Economic Area (EEA), you have
          certain data protection rights. Wesner Software aims to take
          reasonable steps to allow you to correct, amend, delete or limit the
          use of your Personal Data.
        </Typography>
        <Typography variant="body2">
          If you wish to be informed about what Personal Data we hold about you
          and if you want it to be removed from our systems, please contact us.
        </Typography>
        <Typography variant="body2">
          In certain circumstances, you have the following data protection
          rights:
        </Typography>
        <Stack component="ul" gap={1}>
          <Typography variant="body2" component="li">
            <dfn>
              The right to access, update or delete the information we have on
              you.
            </dfn>{' '}
            Whenever made possible, you can access, update or request deletion
            of your Personal Data directly within your account settings section.
            If you are unable to perform these actions yourself, please contact
            us to assist you.
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>The right of rectification.</dfn> You have the right to have
            your information rectified if that information is inaccurate or
            incomplete. The right to object. You have the right to object to our
            processing of your Personal Data.
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>Usage Data </dfn> is data collected automatically either
            generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>The right of restriction.</dfn> You have the right to request
            that we restrict the processing of your personal information.
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>The right to data portability.</dfn> You have the right to be
            provided with a copy of the information we have on you in a
            structured, machine-readable and commonly used format.
          </Typography>
          <Typography variant="body2" component="li">
            <dfn>The right to withdraw consent.</dfn> You also have the right to
            withdraw your consent at any time where Wesner Software relied on
            your consent to process your personal information.
          </Typography>
        </Stack>
        <Typography variant="body2">
          Please note that we may ask you to verify your identity before
          responding to such requests.
        </Typography>
        <Typography variant="body2">
          You have the right to complain to a Data Protection Authority about
          our collection and use of your Personal Data. For more information,
          please contact your local data protection authority in the European
          Economic Area (EEA).
        </Typography>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Service Providers
        </Typography>
        <Typography variant="body2">
          We may employ third party companies and individuals to facilitate our
          Service (“Service Providers”), provide the Service on our behalf,
          perform Service-related services or assist us in analysing how our
          Service is used.
        </Typography>
        <Typography variant="body2" mb={{ xs: 1, md: 2 }}>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </Typography>
        <Stack gap={1}>
          <Typography variant={subtitleVariant} color="grey.900">
            Analytics Providers
          </Typography>
          <Typography variant="body2" mb={{ xs: 1, md: 2 }}>
            We may use third-party Service Providers to monitor and analyse the
            use of our Service.
          </Typography>
          <Stack component="ul" gap={1}>
            <Typography variant="body2" component="li">
              <dfn>Google Analytics </dfn>
              is a web analytics service offered by Google that tracks and
              reports website traffic. Google uses the data collected to track
              and monitor the use of our Service. This data is shared with other
              Google services. Google may use the collected data to
              contextualise and personalise the ads of its own advertising
              network.You can opt-out of having made your activity on the
              Service available to Google Analytics by installing the Google
              Analytics opt-out browser add-on. The add-on prevents the Google
              Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing
              information with Google Analytics about visits activity.For more
              information on the privacy practices of Google, please visit the
              Google Privacy & Terms web page:{' '}
              <Link
                href="https://policies.google.com/privacy?hl=en"
                target="_blank"
                underline="hover"
              >
                https://policies.google.com/privacy?hl=en
              </Link>
            </Typography>
          </Stack>
        </Stack>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Links to Other Sites
        </Typography>
        <Typography variant="body2">
          Our Service may contain links to other sites that are not operated by
          us. If you click a third party link, you will be directed to that
          third party’s site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </Typography>
        <Typography variant="body2">
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </Typography>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Children’s Privacy
        </Typography>
        <Typography variant="body2">
          Our Service does not address anyone under the age of 18 (“Children”).
        </Typography>
        <Typography variant="body2">
          We do not knowingly collect personally identifiable information from
          anyone under the age of 18. If you are a parent or guardian and you
          are aware that your Child has provided us with Personal Data, please
          contact us. If we become aware that we have collected Personal Data
          from children without verification of parental consent, we take steps
          to remove that information from our servers.
        </Typography>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Changes to This Privacy Policy
        </Typography>
        <Typography variant="body2">
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </Typography>
        <Typography variant="body2">
          We will let you know via email and/or a prominent notice on our
          Service, prior to the change becoming effective and update the
          “effective date” at the top of this Privacy Policy.
        </Typography>
        <Typography variant="body2">
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </Typography>
      </Stack>

      <Stack gap={1}>
        <Typography variant={titleVariant} color="grey.900">
          Contact Us
        </Typography>
        <Typography variant="body2">
          If you have any questions about this Privacy Policy, please{' '}
          <MailToLink /> .
        </Typography>
      </Stack>
    </Stack>
  );
}
